# Configuration values
SECRET_KEY = b'\xd6I\xf1\x10\x08\x13\x1e\xea\xed\xaf\xb1\x9cVQ\xa2\x94' # Generated by MeiJade on 12/10/21
MONGODB_HOST = "mongodb://localhost:27017/Flext"

# NOTE: Hosting the DB on the localhost is fine *when we're testing locally*. When we actually deploy our 
# app to the web on Heroku, we'll have to change where we host the DB. Refer to the 12/3/21 slides to 
# learn how to do that.
